import { ICoffe } from './@types/coffe';

export const coffeeList: ICoffe[] = [
	{
		title: 'Expresso Tradicional',
		description: 'O tradicional café feito com água quente e grãos moídos',
		price: '9.9',
		tags: ['Tradicional'],
		url: '/images/Expresso.png',
	},
	{
		title: 'Expresso Americano',
		description: 'Expresso diluído, menos intenso que o tradicional',
		price: '9.9',
		tags: [],
		url: '/images/Americano.png',
	},
	{
		title: 'Expresso Cremoso',
		description: 'Café expresso tradicional com espuma cremosa',
		price: '9.9',
		tags: [],
		url: '/images/Expresso_Cremoso.png',
	},
	{
		title: 'Expresso Gelado',
		description: 'Bebida preparada com café expresso e cubos de gelo',
		price: '9.9',
		tags: ['Tradicional', 'Gelado'],
		url: '/images/Cafe_Gelado.png',
	},
	{
		title: 'Café com Leite',
		description: 'Meio a meio de expresso tradicional com leite vaporizado',
		price: '9.9',
		tags: ['Tradicional', 'Com leite'],
		url: '/images/Cafe_com_Leite.png',
	},
	{
		title: 'Latte',
		description: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
		price: '9.9',
		tags: ['Tradicional', 'Com leite'],
		url: '/images/Latte.png',
	},
	{
		title: 'Capuccino',
		description: 'Bebida com canela feita de doses iguais de café, leite e espuma',
		price: '9.9',
		tags: ['Tradicional', 'Com leite'],
		url: '/images/Capuccino.png',
	},
	{
		title: 'Macchiato',
		description: 'Café expresso misturado com um pouco de leite quente e espuma',
		price: '9.9',
		tags: ['Tradicional', 'Com leite'],
		url: '/images/Macchiato.png',
	},
	{
		title: 'Mocaccino',
		description: 'Café expresso com calda de chocolate, pouco leite e espuma',
		price: '9.9',
		tags: ['Tradicional', 'Com leite'],
		url: '/images/Mochaccino.png',
	},
	{
		title: 'Chocolate Quente',
		description: 'Bebida feita com chocolate dissolvido no leite quente e café',
		price: '9.9',
		tags: ['Especial', 'Com leite'],
		url: '/images/Chocolate Quente.png',
	},
	{
		title: 'Cubano',
		description: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
		price: '9.9',
		tags: ['Especial', 'Alcoólico', 'Gelado'],
		url: '/images/Cubano.png',
	},
	{
		title: 'Havaiano',
		description: 'Bebida adocicada preparada com café e leite de coco',
		price: '9.9',
		tags: ['Especial'],
		url: '/images/Havaiano.png',
	},
	{
		title: 'Árabe',
		description: 'Bebida preparada com grãos de café e especiarias',
		price: '9.9',
		tags: ['Especial'],
		url: '/images/Árabe.png',
	},
	{
		title: 'Irlandês',
		description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
		price: '9.9',
		tags: ['Especial', 'Alcoólico'],
		url: '/images/Irlandês.png',
	},
];
